import * as Dialog from "@radix-ui/react-dialog";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Activity, CircleStop, FileText, HardDrive, Info, Play, RefreshCw, RotateCw, Search, ServerCog, ShieldAlert, Waypoints } from "lucide-react";
import { useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import { Button } from "../../components/ui/Button";
import { api } from "../../lib/api";
import { errorMessage } from "../../lib/errors";
import { formatBytes, formatDuration } from "../../lib/format";
import { pushNotice } from "../../lib/noticeStore";
import type { OperationsSnapshot, StorageSnapshot, TerminationResult } from "../../types/server";

type View = "all" | "ports" | "processes" | "services" | "storage";
type Target = { pid: number; port?: number; command: string; unit?: string | null };
type ServiceAction = "start" | "stop" | "restart" | "enable" | "disable";

/** 展示真实端口、进程和 systemd 状态，并把破坏性动作限制在确认流程内。 */
export function OperationsPage() {
  const { serverId = "" } = useParams();
  const [query, setQuery] = useState("");
  const [view, setView] = useState<View>("all");
  const [target, setTarget] = useState<Target | null>(null);
  const [force, setForce] = useState(false);
  const [privileged, setPrivileged] = useState(false);
  const [privilegedScan, setPrivilegedScan] = useState(false);
  const [result, setResult] = useState<TerminationResult | null>(null);
  const [serviceActionTarget, setServiceActionTarget] = useState<{ name: string; action: ServiceAction } | null>(null);
  const [serviceDetail, setServiceDetail] = useState<Awaited<ReturnType<typeof api.serviceDetail>> | null>(null);
  const [serviceLogs, setServiceLogs] = useState<Awaited<ReturnType<typeof api.serviceLogs>> | null>(null);
  const profile = useQuery({ queryKey: ["server", serverId], queryFn: () => api.getServer(serverId) });
  const operations = useQuery({ queryKey: ["operations", serverId, privilegedScan], queryFn: () => api.operations(serverId, privilegedScan), refetchInterval: 10_000 });
  const storage = useQuery<StorageSnapshot>({ queryKey: ["storage", serverId], queryFn: () => api.storage(serverId), enabled: Boolean(serverId) && view === "storage" });
  const terminate = useMutation({ mutationFn: () => api.terminateProcess({ serverId, pid: target!.pid, port: target?.port, force, privileged }), onSuccess: async (value) => { setResult(value); setTarget(null); setForce(false); setPrivileged(false); await operations.refetch(); } });
  const service = useMutation({ mutationFn: ({ name, action }: { name: string; action: ServiceAction }) => api.manageService(serverId, name, action), onSuccess: () => operations.refetch() });
  const detail = useMutation({ mutationFn: (name: string) => api.serviceDetail(serverId, name), onSuccess: setServiceDetail });
  const logs = useMutation({ mutationFn: (name: string) => api.serviceLogs(serverId, name), onSuccess: setServiceLogs });
  const filtered = useMemo(() => filterSnapshot(operations.data, query), [operations.data, query]);

  return <section className="operations-page">
    <div className="page-toolbar">{profile.data?.sudoMode !== "none" && <label className="scan-toggle"><input type="checkbox" checked={privilegedScan} onChange={(event) => setPrivilegedScan(event.target.checked)} /> sudo 重扫</label>}<Button variant="secondary" onClick={() => operations.refetch()} disabled={operations.isFetching}><RefreshCw className={operations.isFetching ? "spin" : ""} size={14} /> 重新扫描</Button></div>
    <div className="operations-toolbar"><label><Search size={16} /><input autoFocus={view !== "storage"} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索 8080、node、nginx、PID 或 service" /></label><div>{(["all", "ports", "processes", "services", "storage"] as View[]).map((value) => <button key={value} className={view === value ? "active" : ""} onClick={() => setView(value)}>{({ all: "全部", ports: "监听端口", processes: "进程", services: "服务", storage: "磁盘与挂载" })[value]}</button>)}</div></div>
    {operations.isLoading && <div className="page-state">正在从 ps、ss/lsof 与 systemd 读取真实状态…</div>}
    {operations.error && <div className="operation-error-panel"><Info size={19} /><div><strong>运行现场读取失败</strong><p>{errorMessage(operations.error)}。请确认 SSH 会话仍在线后重新扫描。</p></div><Button size="sm" variant="secondary" onClick={() => operations.refetch()}>重新扫描</Button></div>}
    {result && <div className={`operation-result ${result.processExited && result.portReleased !== false ? "is-success" : ""}`}><Activity size={16} /><span>已发送 SIG{result.signal}：PID {result.pid} {result.processExited ? "已退出" : "仍在运行"}{result.portReleased !== null ? `，端口${result.portReleased ? "已释放" : "仍被占用"}` : ""}</span><button onClick={() => setResult(null)}>关闭</button></div>}
    {operations.data?.portsWarning && <div className="operation-result"><Info size={16} /><span>{operations.data.portsWarning}（来源：{operations.data.portsSource}）</span><button onClick={() => operations.refetch()}>重新扫描</button></div>}
    {operations.data && <div className="operations-content">
      {(view === "all" || view === "ports") && <section className="operations-section"><header><Waypoints size={15} /><strong>监听端口</strong><span>{filtered.ports.length}</span></header><div className="ops-table ports-table"><div className="ops-head"><span>协议</span><span>地址</span><span>端口</span><span>进程</span><span>PID</span><span>操作</span></div>{filtered.ports.map((port, index) => <div className="ops-row" key={`${port.protocol}:${port.localAddress}:${port.port}:${index}`}><span className="protocol-badge">{port.protocol}</span><span className="mono">{port.localAddress}</span><strong>{port.port}</strong><span>{port.processName ?? (port.processVisible ? "—" : "权限不足")}</span><span className="mono">{port.pid ?? "—"}</span><span>{port.pid && <Button variant="danger" size="sm" onClick={() => setTarget({ pid: port.pid!, port: port.port, command: port.processName ?? `PID ${port.pid}` })}><CircleStop size={13} /> 释放端口</Button>}</span></div>)}</div></section>}
      {(view === "all" || view === "processes") && <section className="operations-section"><header><Activity size={15} /><strong>进程</strong><span>{filtered.processes.length}</span></header><div className="ops-table process-table"><div className="ops-head"><span>PID</span><span>用户</span><span>CPU</span><span>内存</span><span>运行时间</span><span>命令</span><span>操作</span></div>{filtered.processes.slice(0, 300).map((process) => <div className="ops-row" key={process.pid}><span className="mono">{process.pid}</span><span>{process.user}</span><span>{process.cpuPercent.toFixed(1)}%</span><span>{formatBytes(process.rssBytes)}</span><span>{formatDuration(process.elapsedSeconds)}</span><span className="command-cell" title={process.command}><strong>{process.name}</strong><small>{process.command}</small></span><span>{process.pid > 1 && <Button variant="ghost" size="sm" onClick={() => setTarget({ pid: process.pid, command: process.command, unit: process.systemdUnit })}>结束</Button>}</span></div>)}</div></section>}
      {(view === "all" || view === "services") && <section className="operations-section"><header><ServerCog size={15} /><strong>systemd 服务</strong><span>{filtered.services.length}</span></header><div className="ops-table services-table"><div className="ops-head"><span>单元</span><span>状态</span><span>说明</span><span>操作</span></div>{filtered.services.map((unit) => <div className="ops-row" key={unit.name}><strong className="mono">{unit.name}</strong><span className={`unit-state is-${unit.active}`}>{unit.active} / {unit.sub}</span><span>{unit.description}</span><span className="service-actions">{unit.active === "active" ? <Button variant="ghost" size="sm" onClick={() => setServiceActionTarget({ name: unit.name, action: "stop" })}><CircleStop size={12} /> 停止</Button> : <Button variant="ghost" size="sm" onClick={() => setServiceActionTarget({ name: unit.name, action: "start" })}><Play size={12} /> 启动</Button>}<Button variant="ghost" size="sm" onClick={() => setServiceActionTarget({ name: unit.name, action: "restart" })}><RotateCw size={12} /> 重启</Button><Button variant="ghost" size="sm" onClick={() => detail.mutate(unit.name)}><Info size={12} /> 详情</Button><Button variant="ghost" size="sm" onClick={() => logs.mutate(unit.name)}><FileText size={12} /> 日志</Button></span></div>)}</div></section>}
    </div>}
    {view === "storage" && <StoragePanel snapshot={storage.data} loading={storage.isLoading} error={storage.error ? errorMessage(storage.error) : null} onRefresh={() => void storage.refetch()} />}
    <Dialog.Root open={!!serviceActionTarget} onOpenChange={(open) => !open && setServiceActionTarget(null)}><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="dialog-content dialog-content--narrow confirm-dialog"><div className="destructive-icon"><ShieldAlert size={22} /></div><Dialog.Title>确认 systemd 操作</Dialog.Title><Dialog.Description>将对 {serviceActionTarget?.name} 执行 {serviceActionTarget?.action}，随后验证单元状态。</Dialog.Description>{service.error && <div className="form-error">{errorMessage(service.error)}</div>}<div className="dialog-actions"><Button variant="ghost" onClick={() => setServiceActionTarget(null)}>取消</Button><Button variant="ghost" onClick={() => serviceActionTarget && service.mutate({ ...serviceActionTarget, action: "enable" }, { onSuccess: () => setServiceActionTarget(null) })} disabled={service.isPending}>启用开机自启</Button><Button variant="ghost" onClick={() => serviceActionTarget && service.mutate({ ...serviceActionTarget, action: "disable" }, { onSuccess: () => setServiceActionTarget(null) })} disabled={service.isPending}>禁用开机自启</Button><Button variant={serviceActionTarget?.action === "stop" ? "danger" : "primary"} onClick={() => { if (serviceActionTarget) service.mutate(serviceActionTarget, { onSuccess: () => setServiceActionTarget(null) }); }} disabled={service.isPending}>{service.isPending ? "执行并验证中…" : "确认执行"}</Button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
    <Dialog.Root open={!!serviceDetail} onOpenChange={(open) => !open && setServiceDetail(null)}><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="dialog-content dialog-content--narrow"><div className="dialog-header"><div><Dialog.Title>服务详情</Dialog.Title><Dialog.Description>{serviceDetail?.name}</Dialog.Description></div><Dialog.Close asChild><button className="icon-control" aria-label="关闭">×</button></Dialog.Close></div>{serviceDetail && <dl className="process-confirm"><div><dt>状态</dt><dd>{serviceDetail.active} / {serviceDetail.sub}</dd></div><div><dt>主 PID</dt><dd>{serviceDetail.mainPid ?? "—"}</dd></div><div><dt>Unit 文件</dt><dd className="mono">{serviceDetail.fragmentPath || "—"}</dd></div><div><dt>启用状态</dt><dd>{serviceDetail.unitFileState || "—"}</dd></div><div><dt>说明</dt><dd>{serviceDetail.description || "—"}</dd></div></dl>}</Dialog.Content></Dialog.Portal></Dialog.Root>
    <Dialog.Root open={!!serviceLogs} onOpenChange={(open) => !open && setServiceLogs(null)}><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="dialog-content docker-logs-dialog"><div className="dialog-header"><div><Dialog.Title>服务日志</Dialog.Title><Dialog.Description>{serviceLogs?.name} · 最近 200 行</Dialog.Description></div><Dialog.Close asChild><button className="icon-control" aria-label="关闭">×</button></Dialog.Close></div><pre className="docker-logs">{serviceLogs?.output}</pre></Dialog.Content></Dialog.Portal></Dialog.Root>
    <Dialog.Root open={!!target} onOpenChange={(open) => !open && setTarget(null)}><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="dialog-content dialog-content--narrow confirm-dialog"><div className="destructive-icon"><ShieldAlert size={22} /></div><Dialog.Title>{target?.port ? `释放端口 ${target.port}` : `结束 PID ${target?.pid}`}</Dialog.Title><Dialog.Description>将向 PID {target?.pid} 发送 {force ? "SIGKILL（强制）" : "SIGTERM（优雅退出）"}，然后重新扫描验证结果。</Dialog.Description><dl className="process-confirm"><div><dt>命令</dt><dd>{target?.command}</dd></div>{target?.unit && <div><dt>systemd</dt><dd>{target.unit}（建议优先停止服务）</dd></div>}</dl><div className="terminate-options"><label className="force-toggle"><input type="checkbox" checked={force} onChange={(event) => setForce(event.target.checked)} /> 强制使用 SIGKILL</label>{profile.data?.sudoMode !== "none" && <label className="force-toggle"><input type="checkbox" checked={privileged} onChange={(event) => setPrivileged(event.target.checked)} /> 使用已配置的 sudo</label>}</div>{terminate.error && <div className="form-error">{errorMessage(terminate.error)}</div>}<div className="dialog-actions"><Button variant="ghost" onClick={() => setTarget(null)}>取消</Button><Button variant="danger" onClick={() => terminate.mutate()} disabled={terminate.isPending}>{terminate.isPending ? "正在验证…" : force ? "强制结束并验证" : "结束并验证"}</Button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
  </section>;
}

function filterSnapshot(value: OperationsSnapshot | undefined, query: string): OperationsSnapshot {
  if (!value) return { processes: [], ports: [], portsSource: "unknown", portsWarning: null, services: [] };
  const needle = query.trim().toLocaleLowerCase();
  if (!needle) return value;
  return {
    processes: value.processes.filter((process) => [process.pid, process.ppid, process.user, process.name, process.command, process.systemdUnit].some((item) => String(item ?? "").toLocaleLowerCase().includes(needle))),
    ports: value.ports.filter((port) => [port.port, port.pid, port.protocol, port.localAddress, port.processName].some((item) => String(item ?? "").toLocaleLowerCase().includes(needle))),
    portsSource: value.portsSource,
    portsWarning: value.portsWarning,
    services: value.services.filter((unit) => [unit.name, unit.active, unit.sub, unit.description].some((item) => item.toLocaleLowerCase().includes(needle))),
  };
}

/** 展示远端磁盘、挂载点和 fstab，并把变更交给后端固定命令模板。 */
function StoragePanel({ snapshot, loading, error, onRefresh }: { snapshot?: StorageSnapshot; loading: boolean; error: string | null; onRefresh: () => void }) {
  const serverId = useParams().serverId ?? "";
  const [action, setAction] = useState<"mount" | "add_fstab">("mount");
  const [source, setSource] = useState("");
  const [mountpoint, setMountpoint] = useState("");
  const [filesystem, setFilesystem] = useState("ext4");
  const [options, setOptions] = useState("defaults");
  const [selected, setSelected] = useState<{ action: "unmount" | "remove_fstab"; source: string; mountpoint: string } | null>(null);
  const mutation = useMutation({
    mutationFn: (input: { action: "mount" | "unmount" | "add_fstab" | "remove_fstab"; source?: string; mountpoint: string; filesystem?: string; options?: string }) => api.storageAction({ ...input, confirmed: true, serverId }),
    onSuccess: (value) => { setSelected(null); setSource(""); setMountpoint(""); pushNotice("success", `存储操作完成：${value.mountpoint}`); onRefresh(); },
  });
  const submit = () => {
    if (!mountpoint.trim() || (action !== "mount" && action !== "add_fstab" ? false : !source.trim())) return;
    if (!window.confirm(action === "mount" ? `确认挂载 ${source} 到 ${mountpoint}？` : `确认写入 /etc/fstab：${source} → ${mountpoint}？`)) return;
    mutation.mutate({ action, source: source.trim(), mountpoint: mountpoint.trim(), filesystem, options });
  };
  const confirmSelected = () => {
    if (!selected || !window.confirm(selected.action === "unmount" ? `确认卸载 ${selected.mountpoint}？` : `确认从 /etc/fstab 删除 ${selected.source} → ${selected.mountpoint}？`)) return;
    mutation.mutate({ ...selected });
  };
  return <div className="operations-content storage-content">
    {snapshot?.topology && <section className="operations-section topology-strip"><header><ServerCog size={15} /><strong>存储拓扑</strong><span>块设备摘要</span></header><div className="topology-grid"><div className="topology-chip"><HardDrive size={14} /><span>磁盘</span><strong>{snapshot.topology.disks}</strong></div><div className="topology-chip"><Waypoints size={14} /><span>分区</span><strong>{snapshot.topology.partitions}</strong></div><div className="topology-chip"><ShieldAlert size={14} /><span>RAID 阵列</span><strong>{snapshot.topology.raidArrays}</strong></div><div className="topology-chip"><ServerCog size={14} /><span>LVM 卷</span><strong>{snapshot.topology.lvmVolumes}</strong></div><div className="topology-chip"><Info size={14} /><span>其他设备</span><strong>{snapshot.topology.otherDevices}</strong></div></div></section>}
    <section className="operations-section"><header><HardDrive size={15} /><strong>块设备</strong><span>{snapshot?.devices.length ?? 0}</span><Button size="sm" variant="secondary" onClick={onRefresh} disabled={loading}><RefreshCw size={13} className={loading ? "spin" : ""} />刷新</Button></header>{loading && <div className="page-state">正在读取 lsblk、findmnt 和 fstab…</div>}{error && <div className="operation-error-panel"><Info size={17} /><span>{error}</span><Button size="sm" variant="secondary" onClick={onRefresh}>重试</Button></div>}{snapshot && <div className="ops-table storage-table"><div className="ops-head"><span>设备</span><span>类型</span><span>文件系统</span><span>容量</span><span>挂载点</span><span>状态</span></div>{snapshot.devices.map((device) => <div className="ops-row" key={device.path}><strong className="mono">{device.path}</strong><span>{device.kind}</span><span>{device.filesystem ?? "—"}</span><span>{formatBytes(device.sizeBytes)}</span><span className="mono">{device.mountpoint ?? "—"}</span><span>{device.readonly ? "只读" : device.removable ? "可移除" : "可写"}</span></div>)}</div>}</section>
    <section className="operations-section"><header><Waypoints size={15} /><strong>当前挂载</strong><span>{snapshot?.mounts.length ?? 0}</span></header>{snapshot?.mounts.length ? <div className="ops-table storage-table"><div className="ops-head"><span>挂载点</span><span>来源</span><span>文件系统</span><span>使用率</span><span>选项</span><span>操作</span></div>{snapshot.mounts.map((mount) => <div className="ops-row" key={`${mount.mountpoint}:${mount.source}`}><strong className="mono">{mount.mountpoint}</strong><span className="mono">{mount.source}</span><span>{mount.filesystem}</span><span>{mount.totalBytes ? `${mount.usagePercent.toFixed(0)}%` : "—"}</span><span className="mono">{mount.options}</span><Button size="sm" variant="danger" disabled={mount.mountpoint === "/"} onClick={() => setSelected({ action: "unmount", source: mount.source, mountpoint: mount.mountpoint })}>卸载</Button></div>)}</div> : <div className="empty-panel empty-panel--small"><HardDrive size={18} /><span>没有返回挂载点。</span></div>}</section>
    <section className="operations-section"><header><FileText size={15} /><strong>/etc/fstab</strong><span>{snapshot?.fstab.length ?? 0}</span></header>{snapshot?.fstab.length ? <div className="ops-table storage-table"><div className="ops-head"><span>行</span><span>来源</span><span>挂载点</span><span>文件系统</span><span>选项</span><span>操作</span></div>{snapshot.fstab.map((entry) => <div className="ops-row" key={`${entry.lineNumber}:${entry.mountpoint}`}><span className="mono">{entry.lineNumber}</span><span className="mono">{entry.source}</span><span className="mono">{entry.mountpoint}</span><span>{entry.filesystem}</span><span className="mono">{entry.options}</span><Button size="sm" variant="danger" onClick={() => setSelected({ action: "remove_fstab", source: entry.source, mountpoint: entry.mountpoint })}>移除</Button></div>)}</div> : <div className="empty-panel empty-panel--small"><FileText size={18} /><span>没有可识别的 fstab 条目。</span></div>}</section>
    <section className="operations-section storage-form"><header><div><span className="section-kicker">Controlled change</span><strong>挂载 / 写入 fstab</strong></div><HardDrive size={15} /></header><div className="storage-form-grid"><label><span>操作</span><select value={action} onChange={(event) => setAction(event.target.value as "mount" | "add_fstab")}><option value="mount">立即挂载</option><option value="add_fstab">加入 /etc/fstab（不立即挂载）</option></select></label><label><span>设备 / UUID / LABEL</span><input value={source} onChange={(event) => setSource(event.target.value)} placeholder="/dev/sdb1 或 UUID=…" /></label><label><span>挂载点</span><input value={mountpoint} onChange={(event) => setMountpoint(event.target.value)} placeholder="/mnt/data" /></label><label><span>文件系统</span><select value={filesystem} onChange={(event) => setFilesystem(event.target.value)}><option>ext4</option><option>xfs</option><option>btrfs</option><option>vfat</option><option>nfs</option><option>cifs</option><option>auto</option></select></label><label><span>挂载选项</span><input value={options} onChange={(event) => setOptions(event.target.value)} placeholder="defaults,noatime" /></label><Button variant="primary" onClick={submit} disabled={mutation.isPending || !source.trim() || !mountpoint.trim()}>{mutation.isPending ? "执行中…" : action === "mount" ? "挂载" : "写入 fstab"}</Button></div>{mutation.error && <div className="form-error">{errorMessage(mutation.error)}</div>}<p className="security-note"><ShieldAlert size={15} /><span>后端会再次校验路径、文件系统和选项；写入 fstab 前先备份并执行 dry-run 验证，关键系统挂载点禁止卸载。</span></p></section>
    {selected && <div className="operation-result"><ShieldAlert size={16} /><span>待确认：{selected.action === "unmount" ? "卸载" : "从 fstab 移除"} {selected.mountpoint}</span><Button size="sm" variant="danger" onClick={confirmSelected} disabled={mutation.isPending}>确认执行</Button><Button size="sm" variant="ghost" onClick={() => setSelected(null)}>取消</Button></div>}
    {snapshot?.warnings.map((warning) => <div className="warning-panel" key={warning}><Info size={15} /><span>{warning}</span></div>)}
  </div>;
}
