//! 由 scripts/gen-appstore-meta.py 生成：全部应用官方元数据 (key/name/description/category)。
//! 来源：1Panel-dev/appstore dev 分支 apps/*/data.yml（name、description、tags）。
//! 重新生成：python scripts/gen-appstore-meta.py <appstore 源码目录>

#[derive(Debug, Clone, Copy)]
pub struct CatalogMeta {
    pub key: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub category: &'static str,
}

/// 按 key 查找官方元数据；未命中返回 None（调用方使用兜底文案）。
pub fn for_key(key: &str) -> Option<&'static CatalogMeta> {
    CATALOG_META.iter().find(|meta| meta.key == key)
}

const CATALOG_META: &[CatalogMeta] = &[
    CatalogMeta { key: "2fauth", name: "2FAuth", description: "管理双因素身份验证（2FA）帐户并生成安全代码的 Web 应用程序", category: "安全" },
    CatalogMeta { key: "act_runner", name: "Act Runner", description: "Gitea Actions 的 Runner", category: "DevOps" },
    CatalogMeta { key: "adguardhome", name: "AdGuardHome", description: "网络范围内的广告和跟踪器阻止 DNS 服务器", category: "安全" },
    CatalogMeta { key: "adminer", name: "Adminer", description: "PHP 轻量级数据库管理工具", category: "开发工具" },
    CatalogMeta { key: "affine", name: "AFFiNE", description: "将文档、白板和数据库完全整合的工作空间", category: "实用工具" },
    CatalogMeta { key: "ai-portal", name: "1Panel AI 门户", description: "面向 1Panel 企业版，为用户提供自助式的 API Key 管理、技能市场和 MCP 市场能力", category: "AI" },
    CatalogMeta { key: "alist", name: "AList", description: "支持多存储的文件列表程序和私人网盘", category: "实用工具" },
    CatalogMeta { key: "answer", name: "Answer", description: "适用于任何规模团队的问答平台软件", category: "建站" },
    CatalogMeta { key: "arcadia", name: "Arcadia", description: "写脚本、跑定时任务、服务托管、消息聚合、AI Agent 运行基座，一个面板搞定全流程", category: "DevOps" },
    CatalogMeta { key: "archivebox", name: "ArchiveBox", description: "开源自托管网页存档工具", category: "实用工具" },
    CatalogMeta { key: "artalk", name: "Artalk", description: "一款简洁的自托管评论系统", category: "实用工具" },
    CatalogMeta { key: "astrbot", name: "AstrBot", description: "易于上手的多平台聊天机器人及开发框架", category: "AI" },
    CatalogMeta { key: "audiobookshelf", name: "Audiobookshelf", description: "自托管有声读物和播客服务器", category: "多媒体" },
    CatalogMeta { key: "beszel", name: "Beszel", description: "轻量易用的服务器监控", category: "实用工具" },
    CatalogMeta { key: "bettafish", name: "BettaFish", description: "人人可用的多 Agent 舆情分析助手", category: "AI" },
    CatalogMeta { key: "bililive-go", name: "Bililive-go", description: "支持多种直播平台的直播录制工具", category: "实用工具" },
    CatalogMeta { key: "bitwarden", name: "Bitwarden", description: "开源的密码管理服务", category: "实用工具" },
    CatalogMeta { key: "blinko", name: "Blinko", description: "开源自托管的个人轻量笔记/闪念胶囊工具", category: "其他" },
    CatalogMeta { key: "browserless", name: "Browserless", description: "在 Docker 中部署无头浏览器", category: "实用工具" },
    CatalogMeta { key: "bytebase", name: "Bytebase", description: "开源数据库 DevOps 解决方案", category: "DevOps" },
    CatalogMeta { key: "caddy", name: "Caddy", description: "快速且可扩展的多平台 HTTP/1-2-3 Web 服务器，支持自动启用 HTTPS", category: "Web 服务器" },
    CatalogMeta { key: "calibre-web", name: "Calibre-Web", description: "用于浏览、阅读和下载 Calibre 数据库中存储的电子书的 Web 应用程序", category: "多媒体" },
    CatalogMeta { key: "casdoor", name: "Casdoor", description: "支持 OAuth 2.0、OIDC、SAML 和 CAS 的 Web UI 优先的 IAM/SSO 平台", category: "安全" },
    CatalogMeta { key: "certd", name: "Certd", description: "开源免费的证书管理工具", category: "实用工具" },
    CatalogMeta { key: "certimate", name: "Certimate", description: "一个安全、简便的 SSL 证书管理解决方案", category: "实用工具" },
    CatalogMeta { key: "changedetectionio", name: "Changedetection.io", description: "免费开源网站变更检测、网站观察、补货监控和通知服务", category: "实用工具" },
    CatalogMeta { key: "chatgpt-next-web", name: "ChatGPT-Next-Web", description: "一键拥有你自己的跨平台 ChatGPT/Gemini 应用", category: "AI" },
    CatalogMeta { key: "clawswarm", name: "ClawSwarm", description: "面向 OpenClaw 的开源群体智能协作编排系统", category: "AI" },
    CatalogMeta { key: "clickhouse", name: "ClickHouse", description: "一款免费的大数据分析 DBMS", category: "数据库" },
    CatalogMeta { key: "cloudbeaver", name: "CloudBeaver", description: "云数据库管理器", category: "开发工具" },
    CatalogMeta { key: "cloudflared", name: "cloudflared", description: "Cloudflare Tunnel 客户端", category: "实用工具" },
    CatalogMeta { key: "cloudreve", name: "Cloudreve", description: "支持多家云存储的云盘系统", category: "云存储" },
    CatalogMeta { key: "code-server", name: "code-server", description: "浏览器中的VS Code", category: "开发工具" },
    CatalogMeta { key: "comfyui", name: "ComfyUI", description: "具备可视化节点图界面的强大模块化 AI 创作引擎", category: "AI" },
    CatalogMeta { key: "consul", name: "Consul", description: "分布式、高可用且具有数据中心感知能力的解决方案", category: "中间件" },
    CatalogMeta { key: "convertx", name: "ConvertX", description: "自托管在线文件转换器", category: "实用工具" },
    CatalogMeta { key: "copaw", name: "QwenPaw", description: "阿里开源的 AI 个人助理", category: "AI" },
    CatalogMeta { key: "cordys-crm", name: "Cordys CRM", description: "开源 AI CRM 系统，是 Salesforce 的开源替代", category: "CRM" },
    CatalogMeta { key: "cyberchef", name: "CyberChef", description: "浏览器中的数据编码、解码与分析工具", category: "实用工具" },
    CatalogMeta { key: "dashy", name: "Dashy", description: "专为您打造的可自行托管的个人仪表板", category: "建站" },
    CatalogMeta { key: "dataease", name: "DataEase", description: "人人可用的开源 BI 工具", category: "BI" },
    CatalogMeta { key: "dbhub", name: "DBHub", description: "通用数据库 MCP 服务器连接到 MySQL、PostgreSQL、SQL Server、MariaDB、Oracle", category: "AI" },
    CatalogMeta { key: "dbx", name: "DBX", description: "轻量级跨平台数据库客户端，支持 60+ 种数据库", category: "开发工具" },
    CatalogMeta { key: "ddns-go", name: "ddns-go", description: "简单易用的 DDNS", category: "实用工具" },
    CatalogMeta { key: "deepseek-harness", name: "DeepSeek Harness", description: "DeepSeek 开源智能体开发环境", category: "AI" },
    CatalogMeta { key: "discourse", name: "Discourse", description: "社区讨论的平台。免费、开放、简单。", category: "建站" },
    CatalogMeta { key: "discuz", name: "Discuz!", description: "开源社交建站系统", category: "建站" },
    CatalogMeta { key: "docker-registry", name: "Docker Registry", description: "Docker 镜像存储库", category: "DevOps" },
    CatalogMeta { key: "dockge", name: "Dockge", description: "自托管 - Docker compose.yaml - 面向堆栈的管理器", category: "实用工具" },
    CatalogMeta { key: "docmost", name: "Docmost", description: "开源协作 wiki 与文档软件", category: "建站" },
    CatalogMeta { key: "domain-admin", name: "Domain Admin", description: "域名 SSL 证书监测平台", category: "实用工具" },
    CatalogMeta { key: "dosgame", name: "中文 DOS 游戏", description: "中文 DOS 游戏合集", category: "休闲游戏" },
    CatalogMeta { key: "dotnet", name: ".NET", description: ".NET 运行环境", category: "运行环境" },
    CatalogMeta { key: "drawio", name: "Draw.io", description: "用于一般图表绘制的 JavaScript 客户端编辑器", category: "实用工具" },
    CatalogMeta { key: "dvwa", name: "DVWA", description: "一个用来进行安全脆弱性鉴定的 PHP/MySQL Web 应用平台。", category: "安全" },
    CatalogMeta { key: "easyimage2", name: "EasyImage2.0", description: "一款功能强大无数据库的图床 2.0 版", category: "实用工具" },
    CatalogMeta { key: "easytier", name: "EasyTier", description: "一个简单、安全、去中心化的内网穿透 VPN 组网方案", category: "实用工具" },
    CatalogMeta { key: "elasticsearch", name: "Elasticsearch", description: "免费开放、分布式、RESTful 搜索引擎", category: "数据库" },
    CatalogMeta { key: "emlog", name: "emlog", description: "轻量级开源博客及建站系统。", category: "建站" },
    CatalogMeta { key: "emqx", name: "EMQX", description: "适用于 IoT、IIoT 和联网车辆的最具可扩展性的开源 MQTT 代理", category: "中间件" },
    CatalogMeta { key: "excalidraw", name: "excalidraw", description: "用于绘制手绘风格图表的虚拟白板", category: "实用工具" },
    CatalogMeta { key: "ezbookkeeping", name: "ezBookkeeping", description: "轻量级、自托管的个人财务应用", category: "实用工具" },
    CatalogMeta { key: "filebrowser", name: "File Browser", description: "网页文件浏览器", category: "实用工具" },
    CatalogMeta { key: "filecodebox", name: "FileCodeBox", description: "无需注册，上传文件或文本后通过取件码分享", category: "实用工具" },
    CatalogMeta { key: "firefly-iii", name: "Firefly III", description: "开源的个人财务管理工具", category: "实用工具" },
    CatalogMeta { key: "flarum", name: "Flarum", description: "用于构建优秀社区的简单论坛软件", category: "建站" },
    CatalogMeta { key: "focalboard", name: "Focalboard", description: "Trello、Notion 和 Asana 的开源自托管替代方案", category: "DevOps" },
    CatalogMeta { key: "forgejo", name: "Forgejo", description: "下一代代码托管平台", category: "DevOps" },
    CatalogMeta { key: "forgejo-runner", name: "Forgejo Actions Runner", description: "Forgejo Runner 是连接 Forgejo 实例并运行持续集成作业的守护进程", category: "DevOps" },
    CatalogMeta { key: "freshrss", name: "FreshRSS", description: "自托管的 RSS 和 Atom 源聚合器", category: "实用工具" },
    CatalogMeta { key: "frpc", name: "frp 客户端", description: "专注于内网穿透的高性能反向代理应用", category: "实用工具" },
    CatalogMeta { key: "frps", name: "frp 服务端", description: "专注于内网穿透的高性能反向代理应用", category: "实用工具" },
    CatalogMeta { key: "gatus", name: "Gatus", description: "面向开发者的健康监控面板", category: "实用工具" },
    CatalogMeta { key: "ghost", name: "Ghost", description: "最佳开源博客和电子报平台。", category: "建站" },
    CatalogMeta { key: "gitea", name: "Gitea", description: "新一代的代码托管平台", category: "DevOps" },
    CatalogMeta { key: "gitlab", name: "GitLab", description: "开源的端到端软件开发平台，内置版本控制、问题跟踪、代码审查、CI/CD 等功能", category: "DevOps" },
    CatalogMeta { key: "glance", name: "Glance", description: "一个将所有您的源订阅集中在一个地方的托管仪表板", category: "DevOps" },
    CatalogMeta { key: "go", name: "Go", description: "Go 运行环境", category: "运行环境" },
    CatalogMeta { key: "gotify", name: "Gotify", description: "简单的服务器来发送和接收消息", category: "开发工具" },
    CatalogMeta { key: "grafana", name: "Grafana", description: "用于监控和可观察的开源平台", category: "实用工具" },
    CatalogMeta { key: "greatsql", name: "GreatSQL", description: "可作为 MySQL 或 Percona Server for MySQL 的理想可选替换", category: "数据库" },
    CatalogMeta { key: "gsmanager", name: "GSManager", description: "新一代游戏服务器管理平台", category: "休闲游戏" },
    CatalogMeta { key: "halo", name: "Halo", description: "强大易用的开源建站工具", category: "建站" },
    CatalogMeta { key: "harness", name: "Harness", description: "一个集成源代码管理的端到端开发者平台", category: "DevOps" },
    CatalogMeta { key: "heimdall", name: "Heimdall", description: "应用程序仪表板和启动器", category: "实用工具" },
    CatalogMeta { key: "hermes-agent", name: "Hermes Agent", description: "Nous Research 开源的自托管 AI 智能体", category: "AI" },
    CatalogMeta { key: "home-assistant", name: "Home Assistant", description: "开源家庭自动化，将本地控制和隐私放在首位", category: "实用工具" },
    CatalogMeta { key: "homepage", name: "Homepage", description: "现代的、完全静态的、快速的、安全的、完全代理的、高度可定制的应用程序仪表板", category: "实用工具" },
    CatalogMeta { key: "huginn", name: "Huginn", description: "一个用于构建代理系统的工具，可以为你在线执行自动化任务", category: "实用工具" },
    CatalogMeta { key: "influxdb", name: "InfluxDB", description: "用于指标、事件和实时分析的可扩展数据存储", category: "数据库" },
    CatalogMeta { key: "it-tools", name: "IT-Tools", description: "为开发人员提供方便的在线工具集合，具有出色的用户体验", category: "开发工具" },
    CatalogMeta { key: "jaeger", name: "Jaeger", description: "分布式追踪系统", category: "中间件" },
    CatalogMeta { key: "java", name: "Java", description: "Java 运行环境", category: "运行环境" },
    CatalogMeta { key: "jellyfin", name: "Jellyfin", description: "多媒体应用程序软件套装", category: "多媒体" },
    CatalogMeta { key: "jenkins", name: "Jenkins", description: "开源的持续集成工具", category: "DevOps" },
    CatalogMeta { key: "jsonhero", name: "JSON Hero", description: "开源、美观的 Web JSON 浏览器", category: "实用工具" },
    CatalogMeta { key: "jumpserver", name: "JumpServer", description: "JumpServer 开源堡垒机", category: "安全" },
    CatalogMeta { key: "jupyter-notebook", name: "Jupyter Notebook", description: "支持多语言的交互式编程环境和数据科学笔记本", category: "开发工具" },
    CatalogMeta { key: "kafka", name: "Kafka", description: "开源分布式事件流平台", category: "中间件" },
    CatalogMeta { key: "keycloak", name: "Keycloak", description: "面向现代应用与服务的开源身份和访问管理器", category: "实用工具" },
    CatalogMeta { key: "keydb", name: "KeyDB", description: "Redis 的多线程分支", category: "数据库" },
    CatalogMeta { key: "kibana", name: "Kibana", description: "面向 Elasticsearch 的数据分析与可视化平台", category: "实用工具" },
    CatalogMeta { key: "kirara-agent", name: "Kirara AI", description: "一款支持主流大语言模型、主流聊天平台的聊天的机器人", category: "AI" },
    CatalogMeta { key: "kkfileview", name: "kkFileView", description: "基于 Spring-Boot 的通用文件在线预览项目", category: "实用工具" },
    CatalogMeta { key: "kodbox", name: "Kodbox", description: "可道云推出的企业级私有云存储解决方案", category: "云存储" },
    CatalogMeta { key: "koishi", name: "Koishi", description: "跨平台、可扩展、高性能的聊天机器人框架", category: "实用工具" },
    CatalogMeta { key: "komari", name: "Komari", description: "轻量级的自托管服务器监控工具", category: "实用工具" },
    CatalogMeta { key: "komga", name: "Komga", description: "免费开源的漫画、杂志媒体服务", category: "多媒体" },
    CatalogMeta { key: "koodo-reader", name: "Koodo Reader", description: "一个跨平台的电子书阅读器", category: "多媒体" },
    CatalogMeta { key: "kubepi", name: "KubePi", description: "现代化的 K8s 面板", category: "开发工具" },
    CatalogMeta { key: "langbot", name: "LangBot", description: "开源的 LLM 原生 IM 机器人开发平台", category: "AI" },
    CatalogMeta { key: "langflow", name: "Langflow", description: "用于构建和部署 AI 驱动的智能体与工作流的强大工具", category: "AI" },
    CatalogMeta { key: "linkding", name: "linkding", description: "一款自托管的书签管理器，设计简洁、快速且易于部署", category: "实用工具" },
    CatalogMeta { key: "linux-command", name: "Linux Command", description: "Linux 命令大全搜索工具", category: "开发工具" },
    CatalogMeta { key: "llama-cpp", name: "llama.cpp", description: "使用 GGUF 模型运行本地大语言模型推理服务", category: "AI" },
    CatalogMeta { key: "lobe-chat", name: "LobeChat", description: "开源、现代设计的 ChatGPT/LLMs UI/框架", category: "AI" },
    CatalogMeta { key: "localai", name: "LocalAI", description: "免费的开源 OpenAI 替代品", category: "AI" },
    CatalogMeta { key: "logstash", name: "Logstash", description: "服务器端数据处理管道", category: "实用工具" },
    CatalogMeta { key: "logto", name: "Logto", description: "专为现代应用和 SaaS 产品设计的开源 Auth0 替代品", category: "安全" },
    CatalogMeta { key: "lsky-pro", name: "Lsky-pro", description: "用于在线上传、管理图片的图床程序", category: "云存储" },
    CatalogMeta { key: "maddy-mail", name: "Maddy Mail Server", description: "可组合的多合一邮件服务器", category: "邮件服务" },
    CatalogMeta { key: "mailserver", name: "Mailserver", description: "全栈但简单的容器化邮件服务器", category: "邮件服务" },
    CatalogMeta { key: "manticoresearch", name: "Manticore Search", description: "一个高性能、多存储的数据库，专为搜索和分析而设计", category: "数据库" },
    CatalogMeta { key: "mariadb", name: "MariaDB", description: "著名的 MySQL 分支版本", category: "数据库" },
    CatalogMeta { key: "mattermost", name: "Mattermost", description: "开源安全团队协作平台", category: "实用工具" },
    CatalogMeta { key: "maxkb", name: "MaxKB", description: "强大易用的企业级智能体平台", category: "AI" },
    CatalogMeta { key: "mblog", name: "mBlog", description: "开源自部署的个人微博", category: "建站" },
    CatalogMeta { key: "mcsmanager-daemon", name: "MCSManager", description: "Minecraft 服务器控制面板（后端）", category: "休闲游戏" },
    CatalogMeta { key: "mcsmanager-web", name: "MCSManager", description: "Minecraft 服务器控制面板（前端）", category: "休闲游戏" },
    CatalogMeta { key: "meilisearch", name: "MeiliSearch", description: "开源、快如闪电且高度相关的搜索引擎", category: "实用工具" },
    CatalogMeta { key: "memcached", name: "Memcached", description: "分布式的高速缓存系统", category: "实用工具" },
    CatalogMeta { key: "memos", name: "Memos", description: "轻量级、自托管的备忘录中心", category: "实用工具" },
    CatalogMeta { key: "metabase", name: "Metabase", description: "开源的数据分析和可视化工具", category: "BI" },
    CatalogMeta { key: "metersphere", name: "MeterSphere", description: "新一代的测试管理和接口测试工具", category: "DevOps" },
    CatalogMeta { key: "miniflux", name: "Miniflux", description: "极简主义的 Feed 阅读器", category: "实用工具" },
    CatalogMeta { key: "minio", name: "MinIO", description: "开源的对象存储服务器", category: "中间件" },
    CatalogMeta { key: "mkdocs-material", name: "Material for MkDocs", description: "Markdown 文件托管平台", category: "实用工具" },
    CatalogMeta { key: "mliev-dwz", name: "木雷短网址", description: "高性能的企业级短链接服务平台", category: "实用工具" },
    CatalogMeta { key: "mongo-express", name: "mongo-express", description: "基于 Web 的 MongoDB 管理界面", category: "开发工具" },
    CatalogMeta { key: "mongodb", name: "MongoDB", description: "开源文档数据库", category: "数据库" },
    CatalogMeta { key: "mssql", name: "Microsoft SQL Server", description: "SQL Server 在 Docker 资源中的官方微软存储库", category: "数据库" },
    CatalogMeta { key: "music-tag-web", name: "Music Tag Web", description: "适用于远程与 NAS 音乐库的 Web 音乐标签编辑器", category: "多媒体" },
    CatalogMeta { key: "mysql", name: "MySQL", description: "MySQL 开源关系型数据库", category: "数据库" },
    CatalogMeta { key: "mysql-cluster", name: "MySQL-Cluster", description: "MySQL 一主多从", category: "数据库" },
    CatalogMeta { key: "n8n", name: "n8n", description: "具有原生 AI 能力的 Fair-code 工作流自动化平台", category: "AI" },
    CatalogMeta { key: "nacos", name: "Nacos", description: "动态服务发现、配置管理和服务管理平台", category: "中间件" },
    CatalogMeta { key: "navidrome", name: "Navidrome", description: "基于 Web 的开源音乐收藏服务器和流媒体", category: "多媒体" },
    CatalogMeta { key: "neko", name: "Neko", description: "基于 Docker 和 WebRTC 的自托管虚拟浏览器", category: "实用工具" },
    CatalogMeta { key: "neo4j", name: "Neo4j", description: "世界领先的图数据库", category: "数据库" },
    CatalogMeta { key: "netdata", name: "Netdata", description: "开源实时基础设施监控平台", category: "实用工具" },
    CatalogMeta { key: "new-api", name: "New API", description: "新一代大模型网关与 AI 资产管理系统", category: "AI" },
    CatalogMeta { key: "newsnow", name: "NewsNow", description: "优雅地阅读实时热门新闻", category: "实用工具" },
    CatalogMeta { key: "nextcloud", name: "Nextcloud", description: "Nextcloud 服务器，所有数据的安全家园", category: "云存储" },
    CatalogMeta { key: "nexus", name: "Nexus Repository", description: "开源的软件制品库", category: "DevOps" },
    CatalogMeta { key: "nezha", name: "哪吒监控", description: "开源、轻量、易用的服务器监控与运维工具", category: "实用工具" },
    CatalogMeta { key: "nginx-proxy-manager", name: "Nginx Proxy Manager", description: "Nginx 可视化管理工具", category: "Web 服务器" },
    CatalogMeta { key: "nocobase", name: "NocoBase", description: "可扩展性优先的开源无代码开发平台", category: "开发工具" },
    CatalogMeta { key: "nocodb", name: "NocoDB", description: "无代码数据库平台", category: "数据库" },
    CatalogMeta { key: "node", name: "Node.js", description: "Node.js 运行环境", category: "运行环境" },
    CatalogMeta { key: "node-exporter", name: "Node Exporter", description: "服务器指标导出器", category: "实用工具" },
    CatalogMeta { key: "node-red", name: "Node-RED", description: "用于事件驱动应用的低代码编程", category: "实用工具" },
    CatalogMeta { key: "nodebb", name: "NodeBB", description: "基于 Node.js 的现代化论坛程序", category: "建站" },
    CatalogMeta { key: "npc", name: "NPC", description: "内网穿透代理服务器 NPS 的客户端", category: "其他" },
    CatalogMeta { key: "nps", name: "NPS", description: "轻量级、高性能、功能强大的内网穿透代理服务器", category: "其他" },
    CatalogMeta { key: "ntfy", name: "ntfy", description: "基于 HTTP 的简单 pub-sub 通知服务", category: "开发工具" },
    CatalogMeta { key: "obsidian_livesync", name: "Obsidian LiveSync", description: "Obsidian 在线同步插件", category: "实用工具" },
    CatalogMeta { key: "oceanbase", name: "OceanBase", description: "兼容 MySQL 的单机分布式一体化国产开源数据库", category: "数据库" },
    CatalogMeta { key: "odoo", name: "Odoo", description: "企业一站式管理专家", category: "CRM" },
    CatalogMeta { key: "ollama", name: "Ollama", description: "快速部署并开始使用 Kimi-K2.5、GLM-5、MiniMax、DeepSeek、gpt-oss、Qwen、Gemma 等多种模型", category: "AI" },
    CatalogMeta { key: "ollama-webui", name: "OpenWebUI", description: "用户友好的 AI 界面（支持 Ollama、OpenAI API 等）", category: "AI" },
    CatalogMeta { key: "one-api", name: "One API", description: "OpenAI 接口管理 & 分发系统", category: "AI" },
    CatalogMeta { key: "onedev", name: "OneDev", description: "带有 CI/CD、Kanban 和 Packages 的 Git 服务器", category: "DevOps" },
    CatalogMeta { key: "onlyoffice", name: "ONLYOFFICE Docs", description: "免费的在线办公套件", category: "实用工具" },
    CatalogMeta { key: "openclaw", name: "OpenClaw", description: "开源、自托管的个人 AI 助理", category: "AI" },
    CatalogMeta { key: "opengist", name: "Opengist", description: "一个由 Git 驱动的自托管 Pastebin", category: "DevOps" },
    CatalogMeta { key: "openldap", name: "OpenLDAP", description: "开源的 LDAP(Lightweight Directory Access Protocol) 服务软件", category: "数据库" },
    CatalogMeta { key: "openlist", name: "OpenList", description: "一个支持多种存储的文件列表程序", category: "实用工具" },
    CatalogMeta { key: "openlitespeed", name: "OpenLiteSpeed", description: "高性能、轻量级、开源的 HTTP 服务器", category: "Web 服务器" },
    CatalogMeta { key: "openresty", name: "OpenResty", description: "基于 NGINX 和 LuaJIT 的 Web 平台", category: "Web 服务器" },
    CatalogMeta { key: "openvpn", name: "OpenVPN", description: "开源 VPN 守护进程", category: "实用工具" },
    CatalogMeta { key: "outline", name: "Outline", description: "适合成长型团队的最快知识库，美观、实时协作、功能丰富，并支持 Markdown 格式", category: "实用工具" },
    CatalogMeta { key: "palworld", name: "Palworld Server", description: "幻兽帕鲁服务端", category: "休闲游戏" },
    CatalogMeta { key: "palworld-server-tool", name: "Palworld Server Tool", description: "幻兽帕鲁服务可视化管理工具", category: "休闲游戏" },
    CatalogMeta { key: "pgadmin4", name: "PGAdmin4", description: "PostgreSQL 开源管理工具", category: "开发工具" },
    CatalogMeta { key: "photoprism", name: "PhotoPrism", description: "去中心化网络的人工智能照片应用程序", category: "多媒体" },
    CatalogMeta { key: "php", name: "PHP", description: "PHP 运行环境", category: "运行环境" },
    CatalogMeta { key: "php5", name: "PHP 5", description: "PHP5 运行环境", category: "运行环境" },
    CatalogMeta { key: "php7", name: "PHP 7", description: "PHP7 运行环境", category: "运行环境" },
    CatalogMeta { key: "php8", name: "PHP 8", description: "PHP8 运行环境", category: "运行环境" },
    CatalogMeta { key: "phpmyadmin", name: "phpMyAdmin", description: "MySQL 和 MariaDB 的 Web 界面", category: "开发工具" },
    CatalogMeta { key: "planka", name: "Planka", description: "优雅的开源项目追踪", category: "DevOps" },
    CatalogMeta { key: "portainer-ce", name: "Portainer-CE", description: "图形界面容器管理工具", category: "实用工具" },
    CatalogMeta { key: "postgresql", name: "PostgreSQL", description: "开源关系型数据库", category: "数据库" },
    CatalogMeta { key: "postgresql-cluster", name: "PostgreSQL-Cluster", description: "PostgreSQL 一主多从", category: "数据库" },
    CatalogMeta { key: "prometheus", name: "Prometheus", description: "监控系统和时间序列数据库", category: "数据库" },
    CatalogMeta { key: "python", name: "Python", description: "Python 运行环境", category: "运行环境" },
    CatalogMeta { key: "qbittorrent", name: "qBittorrent", description: "跨平台的开源 BitTorrent 客户端", category: "实用工具" },
    CatalogMeta { key: "qiandao", name: "QD", description: "HTTP 请求定时任务自动执行框架", category: "实用工具" },
    CatalogMeta { key: "qinglong", name: "青龙", description: "定时任务管理平台", category: "实用工具" },
    CatalogMeta { key: "rabbitmq", name: "RabbitMQ", description: "功能丰富的多协议消息传递和流媒体代理", category: "中间件" },
    CatalogMeta { key: "reader", name: "reader", description: "阅读3服务器版", category: "实用工具" },
    CatalogMeta { key: "redis", name: "Redis", description: "高性能的开源键值数据库", category: "数据库" },
    CatalogMeta { key: "redis-cluster", name: "Redis-Cluster", description: "Redis 集群", category: "数据库" },
    CatalogMeta { key: "redis-commander", name: "Redis-Commander", description: "Redis Web 管理工具", category: "开发工具" },
    CatalogMeta { key: "redpanda-console", name: "Redpanda Console", description: "Kafka Web 管理工具", category: "开发工具" },
    CatalogMeta { key: "rocketmq", name: "RocketMQ", description: "云原生消息传递和流媒体平台", category: "中间件" },
    CatalogMeta { key: "roundcube", name: "Roundcube", description: "基于 Web 的多语言 IMAP 邮件客户端", category: "邮件服务" },
    CatalogMeta { key: "rsshub", name: "RSSHub", description: "全球最大的 RSS 网络", category: "实用工具" },
    CatalogMeta { key: "rustdesk", name: "RustDesk", description: "开源的远程桌面软件", category: "实用工具" },
    CatalogMeta { key: "rustfs", name: "RustFS", description: "分布式存储系统", category: "中间件" },
    CatalogMeta { key: "screego", name: "screego", description: "开源屏幕共享工具", category: "实用工具" },
    CatalogMeta { key: "sentinel-dashboard", name: "Sentinel Dashboard", description: "流量控制、熔断降级规则统一配置和管理的入口", category: "中间件" },
    CatalogMeta { key: "sftpgo", name: "SFTPGo", description: "功能齐全且高度可配置的 SFTP 服务器", category: "实用工具" },
    CatalogMeta { key: "showdoc", name: "ShowDoc", description: "一个非常适合 IT 团队的在线 API 文档、技术文档工具", category: "DevOps" },
    CatalogMeta { key: "siyuan", name: "思源笔记", description: "隐私优先的个人知识管理系统", category: "实用工具" },
    CatalogMeta { key: "sonarqube", name: "SonarQube", description: "开源的代码质量管理平台", category: "DevOps" },
    CatalogMeta { key: "sqlbot", name: "SQLBot", description: "基于大模型和 RAG 的智能问数系统", category: "AI" },
    CatalogMeta { key: "stalwart-mail", name: "Stalwart Mail Server", description: "安全且现代的一体化邮件服务器", category: "邮件服务" },
    CatalogMeta { key: "starrocks", name: "StarRocks", description: "新一代极速全场景 MPP 数据库", category: "数据库" },
    CatalogMeta { key: "stirling-pdf", name: "Stirling-PDF", description: "强大的本地托管基于 Web 的 PDF 操作工具", category: "实用工具" },
    CatalogMeta { key: "sub2api", name: "Sub2API", description: "AI API 网关平台，支持订阅配额分发与管理", category: "AI" },
    CatalogMeta { key: "sun-panel", name: "Sun-Panel", description: "一个服务器、NAS 导航面板、首页与浏览器起始页", category: "实用工具" },
    CatalogMeta { key: "synapse", name: "Synapse", description: "开源的 Matrix 家庭服务器，自建聊天服务端", category: "实用工具" },
    CatalogMeta { key: "tailchat", name: "Tailchat", description: "您自己的工作空间中的下一代 noIM 应用程序", category: "实用工具" },
    CatalogMeta { key: "tdengine", name: "TDengine", description: "专为工业物联网（IIoT）场景设计的高性能、可扩展时间序列数据库", category: "数据库" },
    CatalogMeta { key: "teable", name: "Teable", description: "下一代 Airtable 替代方案", category: "实用工具" },
    CatalogMeta { key: "teamspeak", name: "TeamSpeak Server", description: "一款出色的网络语音 (VoIP) 解决方案", category: "实用工具" },
    CatalogMeta { key: "tinyrdm", name: "Tiny RDM", description: "一个现代化轻量级的跨平台 Redis 客户端", category: "开发工具" },
    CatalogMeta { key: "tomcat", name: "Apache Tomcat", description: "开源的 Web 服务器和 Servlet 容器", category: "中间件" },
    CatalogMeta { key: "trendradar", name: "TrendRadar", description: "多平台热点推送", category: "实用工具" },
    CatalogMeta { key: "trilium", name: "Trilium", description: "使用 Trilium Notes 建立个人知识库", category: "实用工具" },
    CatalogMeta { key: "twenty", name: "Twenty", description: "由社区驱动的现代化 Salesforce 替代方案", category: "CRM" },
    CatalogMeta { key: "twikoo", name: "Twikoo", description: "简洁、安全、免费的静态网站评论系统", category: "实用工具" },
    CatalogMeta { key: "typecho", name: "Typecho", description: "基于 PHP 的博客软件", category: "建站" },
    CatalogMeta { key: "typesense", name: "Typesense", description: "速度极快的开源搜索引擎", category: "数据库" },
    CatalogMeta { key: "umami", name: "Umami", description: "Google Analytics 的简单、快速、注重隐私的替代方案", category: "实用工具" },
    CatalogMeta { key: "upage", name: "UPage", description: "基于大模型的可视化网页构建平台", category: "AI" },
    CatalogMeta { key: "uptime-kuma", name: "Uptime Kuma", description: "一款精美的自托管监控工具", category: "实用工具" },
    CatalogMeta { key: "uuwaf", name: "uuWAF", description: "南墙 WEB 应用防火墙", category: "安全" },
    CatalogMeta { key: "valkey", name: "Valkey", description: "高性能开源数据结构服务器", category: "数据库" },
    CatalogMeta { key: "vane", name: "Vane", description: "AI 驱动的智能问答引擎", category: "AI" },
    CatalogMeta { key: "vector", name: "Vector", description: "高性能可观测性数据管道", category: "实用工具" },
    CatalogMeta { key: "verdaccio", name: "Verdaccio", description: "本地私有 NPM 注册中心", category: "DevOps" },
    CatalogMeta { key: "vexdb", name: "VexDB", description: "融合关系数据能力、多路语义检索能力的向量数据库", category: "数据库" },
    CatalogMeta { key: "vllm", name: "vLLM", description: "用于大语言模型的高吞吐量和内存高效的推理和服务引擎", category: "AI" },
    CatalogMeta { key: "waline", name: "Waline", description: "一款简洁、安全的评论系统", category: "实用工具" },
    CatalogMeta { key: "wallos", name: "Wallos", description: "开源个人订阅跟踪器", category: "实用工具" },
    CatalogMeta { key: "watchtower", name: "watchtower", description: "自动更新 Docker 容器基础镜像的工具", category: "实用工具" },
    CatalogMeta { key: "web-check", name: "Web-Check", description: "用于分析任何网站的多合一 OSINT 工具", category: "实用工具" },
    CatalogMeta { key: "wechatmarkdowneditor", name: "WeChat Markdown Editor", description: "一款高度简洁的微信 Markdown 编辑器", category: "实用工具" },
    CatalogMeta { key: "wikijs", name: "Wiki.js", description: "基于 Node.js 构建的现代而强大的 Wiki 应用程序", category: "建站" },
    CatalogMeta { key: "windows", name: "Windows", description: "Docker 容器内的 Windows", category: "实用工具" },
    CatalogMeta { key: "woodpecker", name: "Woodpecker CI", description: "一款简单而强大的 CI/CD 引擎，具备出色的扩展性。", category: "DevOps" },
    CatalogMeta { key: "wordpress", name: "WordPress", description: "著名的开源博客软件和 CMS 系统", category: "建站" },
    CatalogMeta { key: "xiaomusic", name: "XiaoMusic", description: "无限听歌，解放小爱音箱", category: "实用工具" },
    CatalogMeta { key: "yesplaymusic", name: "YesPlayMusic", description: "高颜值的第三方网易云播放器", category: "多媒体" },
    CatalogMeta { key: "yourls", name: "YOURLS", description: "PHP 驱动的标准自托管 URL 缩短器", category: "实用工具" },
    CatalogMeta { key: "zabbix-agent", name: "Zabbix Agent", description: "面向 IT 和 OT 的通用开源可观测性解决方案", category: "实用工具" },
    CatalogMeta { key: "zabbix-proxy", name: "Zabbix Proxy", description: "Zabbix分布式监控代理，适用于多机房、内网隔离监控场景", category: "其他" },
    CatalogMeta { key: "zabbix-server", name: "Zabbix Server", description: "面向 IT 和 OT 的通用开源可观测性解决方案", category: "实用工具" },
    CatalogMeta { key: "zabbix-xinchuang-edition", name: "Zabbix 信创版", description: "Zabbix 信创版", category: "其他" },
    CatalogMeta { key: "zentao", name: "禅道", description: "敏捷（scrum）项目管理系统/工具，永久免费升级", category: "DevOps" },
    CatalogMeta { key: "zfile", name: "ZFile", description: "基于 Java 的在线网盘程序", category: "云存储" },
    CatalogMeta { key: "zitadel", name: "ZITADEL", description: "开源的身份与访问管理（IAM）平台", category: "安全" },
];
